CATEGORY_TAGS = [
    "Rent",
    "Mortgage payments",
    "Home insurance",
    "Property taxes",
    "Maintenance and repairs",
    "Electricity",
    "Water",
    "Gas",
    "Internet",
    "Cable",
    "Fuel",
    "Public transit costs",
    "Vehicle maintenance",
    "Parking fees",
    "Car payments",
    "Food",
    "Groceries",
    "Dining out",
    "Fast food",
    "Health insurance premiums",
    "Doctor visits",
    "Prescriptions",
    "Dental care",
    "Movies",
    "Concerts",
    "Sporting events",
    "Books",
    "Hobbies",
    "Savings account deposits",
    "Retirement contributions",
    "Investment purchases",
    "Tuition",
    "School supplies",
    "Student loans",
    "Online courses",
    "Product sales",
    "Service fees",
    "Royalties",
    "Investment income",
    "Raw materials",
    "Direct labor",
    "Manufacturing supplies",
    "Shipping costs",
    "Salaries and wages",
    "Rent or lease payments",
    "Utility expenses",
    "Marketing and advertising",
    "Professional services (e.g., legal, consulting)",
    "Equipment purchases",
    "Building improvements",
    "Technology upgrades",
    "Income tax",
    "Sales tax",
    "Payroll tax",
    "Property tax",
    "Interest payments",
    "Principal repayments",
    "Travel and entertainment",
    "Insurance premiums",
    "Office supplies",
]

RULES = {
    "coffee": "Dining out",
    "grocery": "Groceries",
    "uber": "Public transit costs",

}


def categorize(description: str) -> str:
    desc = description.lower()
    for keyword, category in RULES.items():
        if keyword in desc:
            return category
    return "Uncategorized"
